- name: install dependencies
  ansible.builtin.dnf:
    name: "{{ dependencies }}"
    state: present
    update_cache: true

- name: start and enable memcached.service
  ansible.builtin.service:
    name: memcached
    enabled: true
    state: started