- name: dependencies
  ansible.builtin.import_tasks:
    file: dependencies.yml

- name: config
  ansible.builtin.import_tasks:
    file: config.yml
  notify: start tomcat

- name: firewall
  ansible.builtin.import_tasks:
    file: firewall.yml