- name: set password for the root account of mariadb
  ansible.builtin.shell:
    cmd: mysqladmin -u root password "{{ db_pass }}"

- name: remove all connection, anonymous user, and test database
  community.mysql.mysql_query:
    login_user: root
    login_password: "{{ db_pass }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    query: "{{ queries }}"
  notify: flush

- name: create database
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ db_pass }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: "{{ db_name }}"
    target: db_backup.sql
    state: import
    chdir: "{{ path_to_project }}/src/main/resources/"

- name: create and grant privileges to a new account
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ db_pass }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    host: "%"
    priv: 'accounts.*:ALL'
    column_case_sensitive: true
    state: present
  notify: flush